plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.ffc.ce3'
    compileSdk 34

    defaultConfig {
        applicationId "dev.ffc.ce3"
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName "0.3.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
