const fs=require('node:fs');

function read(p){return fs.readFileSync(p,'utf8')}
function must(cond,msg){if(!cond)throw new Error(msg)}

const config=read('app/src/main/java/com/ffc/banc888/fly/AppConfig.java');
const shell=read('app/src/main/java/com/ffc/banc888/fly/WebShellController.java');
const activity=read('app/src/main/java/com/ffc/banc888/fly/MainActivity.java');
const session=read('app/src/main/java/com/ffc/banc888/fly/NativeSession.java');
const registry=read('app/src/main/java/com/ffc/banc888/fly/BridgeRegistry.java');
const speech=read('app/src/main/java/com/ffc/banc888/fly/SpeechController.java');
const index=read('app/src/main/assets/index.html');
const bridge=read('app/src/main/assets/native-bridge.js');
const runtime=read('app/src/main/assets/webview-runtime.js');
const threadRouter=read('app/src/main/assets/thread-router.js');
const imageQuality=read('app/src/main/assets/image-quality-core.js');
const capabilityTools=read('app/src/main/assets/capability-tools.js');
const autonomy=read('app/src/main/assets/autonomy-core.js');
const proxy=read('app/src/main/assets/proxy-agent.js');
const manifest=JSON.parse(read('app/src/main/assets/live-manifest.json'));

must(/SHELL_VERSION\s*=\s*75/.test(config),'shell version must be 75 for saved JSON exports');
must(/WEB_RUNTIME_VERSION\s*=\s*7/.test(config),'web runtime version must remain 7');
must(/BRIDGE_SCHEMA\s*=\s*8/.test(config),'bridge schema must be 8 for local model JSON exports');
must(/ASSET_SCHEMA\s*=\s*10/.test(config),'asset schema must be 10 for parallel worker assets exports');
must(config.includes('"webview-runtime.js"'),'runtime asset must be installed and live-updatable');

must(shell.includes('addWebMessageListener'),'origin-scoped WebMessage bridge missing');
must(shell.includes('Collections.singleton(AppConfig.APP_ORIGIN)'),'WebMessage origin rule missing');
must(shell.includes('blocked remote subresource'),'remote subresource policy missing');
must(shell.includes('MIXED_CONTENT_NEVER_ALLOW'),'mixed content policy missing');
must(shell.includes('setAllowFileAccess(false)'),'file access must remain disabled');
must(shell.includes('setAllowContentAccess(false)'),'content access must remain disabled');
must(shell.includes('onRenderProcessGone'),'renderer loss recovery missing');
must(shell.includes('WebRecoveryGuard.tryAcquire'),'bounded recovery guard missing');
must(shell.includes('WebViewRenderProcessClient'),'renderer responsiveness monitor missing');
must(shell.includes('NavigationListener'),'native navigation metrics missing');
must(shell.includes('WebResourceErrorCompat'),'compat error callback missing');
must(shell.includes('__BANC_NATIVE_EPOCH'),'native session epoch injection missing');
must(shell.includes('runtime.capabilities'),'native capability handshake missing');
must(shell.includes('__nativeDispatch'),'Java-to-WebView event dispatch missing');
must(shell.includes('stale-native-session'),'stale WebView session rejection missing');
must(session.includes('long epoch()'),'native session epoch accessor missing');
must(registry.includes('callUiBoolean'),'native speech bridge must synchronously return the Android main-thread result');
must(registry.includes('speech.startListening(language)'),'native speech start bridge missing');
must(registry.includes('speech.stopListening()'),'native speech stop bridge missing');
must(registry.includes('speech.speak(text, language, rate, pitch)'),'native TTS bridge missing');
must(registry.includes('probeMicrophone'),'raw microphone diagnostic bridge missing');
must(speech.includes('pendingSpeechText'),'TTS readiness queue missing');
must(speech.includes('ttsPending'),'TTS pending diagnostics missing');
must(speech.includes('findFallbackVoice'),'TTS fallback voice selection missing');
must(speech.includes('handleTtsFailure'),'TTS retry/error handler missing');
must(speech.includes('ttsLanguageStatus'),'TTS language diagnostics missing');
must(speech.includes('ttsDefaultVoice'),'TTS default-voice diagnostics missing');
must(speech.includes('tts.speak(')&&speech.includes('TextToSpeech.ERROR'),'TTS immediate enqueue failure detection missing');
must(speech.includes('AudioRecord'),'raw microphone capture probe missing');
must(speech.includes('readSamples'),'microphone PCM read diagnostics missing');
must(speech.includes('recognizerReadyAtMs'),'recognizer readiness diagnostics missing');
must(speech.includes('fallbackToSystemRecognizer'),'on-device to system recognizer fallback missing');
must(speech.includes('ready-timeout'),'recognizer readiness watchdog missing');
must(speech.includes('speech-activity-timeout'),'5-second speech activity watchdog missing');
must(speech.includes('EXTRA_AUDIO_SOURCE'),'deterministic recognizer audio-source support missing');
must(speech.includes('startListeningFromAudio'),'instrumentation audio-source entry point missing');
must(speech.includes('5000L'),'speech activity watchdog must remain five seconds');
must(speech.includes('recognitionActivityAtMs'),'speech activity diagnostics missing');
must(index.includes('PCM取得OK'),'UI must distinguish real PCM capture from permission-only state');
must(index.includes('micProbe'),'UI microphone probe diagnostics missing');
must(index.includes('id="flyVoiceLoop" type="checkbox" checked'),'hands-free voice loop must default on');
must(index.includes("agentRegister('research.wiki'"),'general knowledge research tool missing');
must(index.includes('agentResearchQuery'),'conversation research query normalization missing');
must(index.includes('agentWikiText'),'human-readable research answer formatter missing');
must(!index.includes('会話機能を復元しています。何から見ますか？'),'obsolete canned restoration reply must not return');
must(index.includes('bancWanted'),'ordinary questions must not be hijacked by unrelated BANC context');
must(threadRouter.includes("proxy.executeAsync(request,ctx)"),'thread router must send only the latest utterance to intent classification');
must(threadRouter.includes("{goal:visibleText(t,text),threadCode:code(t),context:context(t)}"),'thread context must be separate from latest conversational goal');
must(!threadRouter.includes("quietAgentRun(prompt(x.t,x.q.text))"),'management-wrapped thread prompt must not reach conversational classifier');
must(threadRouter.includes('ffcQuickListen'),'mobile conversation view must expose microphone action without scrolling');
must(config.includes('"image-quality-core.js"'),'image quality core must be a managed runtime asset');
must(config.includes('"autonomy-core.js"'),'autonomy core must be a managed runtime asset');
must(imageQuality.includes('function expand('),'image prompt multi-expansion missing');
must(imageQuality.includes('function evaluate('),'image candidate hard-gate evaluation missing');
must(imageQuality.includes('function rank('),'image candidate ranking missing');
must(imageQuality.includes('CATEGORY_PARTS'),'category-specific image structure rules missing');
must(imageQuality.includes('categoryIntegrity'),'category-specific image integrity gate missing');
must(imageQuality.includes('function evolve('),'evolutionary image candidate breeder missing');
must(capabilityTools.includes('generationTrace'),'multi-generation image search trace missing');
must(capabilityTools.includes('IQ.evolve'),'image search must breed higher-scoring candidates');
must(index.includes("seed+'|layout'"),'O2 seed must affect scene composition');
must(index.includes('renderSeed'),'O2 seed must affect texture generation');
must(imageQuality.includes('layoutX'),'image evolution must search horizontal composition');
must(imageQuality.includes('scaleBias'),'image evolution must search subject scale');
must(capabilityTools.includes('layoutX:v.layoutX'),'evolved geometry genes must reach the renderer');
must(index.includes('generationOptions'),'O2 must apply evolved generation options');
must(index.includes('1024'),'O2 must support 1024-class output');
must(index.includes('o2xEntityVisualMetrics'),'rendered entity-part measurement missing');
must(index.includes('o2xRegionMetrics'),'rendered part pixel statistics missing');
must(index.includes('explicitImage'),'image generation must require an explicit visual request');
must(index.includes('sceneDetail:detail'),'O2 candidate scene diagnostics missing');

must(!activity.includes('webView.saveState('),'WebView state must not be serialized into Activity bundles');
must(!activity.includes('webView.restoreState('),'oversized Chromium state restore path must remain disabled');

must(bridge.includes('window.AndroidRuntime'),'async native runtime API missing');
must(bridge.includes("post('runtime.status')"),'runtime status message missing');
must(bridge.includes("post('runtime.capabilities')"),'runtime capability request missing');
must(bridge.includes('__nativeDispatch'),'native push receiver missing');
must(bridge.includes('epoch'),'bridge session epoch missing');
must(bridge.includes('probeMicrophone'),'WebView microphone probe wrapper missing');
must(runtime.includes('window.FFC_WEBVIEW_RUNTIME'),'WebView health runtime missing');
must(runtime.includes('uiSettingsBody'),'WebView diagnostics must live inside settings drawer');
must(runtime.includes('WebView / Java連携'),'integrated Java/WebView panel missing');
must(runtime.includes("runtime.heartbeat"),'runtime heartbeat missing');
must(runtime.includes('unhandledrejection'),'promise error monitoring missing');
must(runtime.includes("PerformanceObserver"),'long-task monitoring missing');

must(autonomy.includes('class Autonomy'),'autonomy learner missing');
must(autonomy.includes('recordEpisode'),'autonomous skill acquisition missing');
must(autonomy.includes('matchSkill'),'autonomous skill reuse missing');
must(proxy.includes('learnedProposal'),'proxy must consult learned skills');
must(proxy.includes('baseCandidateProposal'),'proxy must autonomize built-in tool routes');
must(proxy.includes('feedbackEvent'),'proxy must feed outcomes back into learning');
must(manifest.bridgeSchema===8&&manifest.assetSchema===10&&manifest.minShellVersion===75,'live manifest schema drift');
must(Object.hasOwn(manifest.files,'webview-runtime.js'),'live manifest missing webview-runtime.js');

console.log('webview-runtime-contract: PASS');
