plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ffc.banc888.fly'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ffc.banc888.fly'
        minSdk 26
        targetSdk 35
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        versionCode 74
        versionName '7.0.4-webview-voice-capture'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.16.0'
    implementation 'androidx.core:core:1.15.0'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:core:1.6.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
}
